# Introduction to Quality Data & Engineering with Python
## Lecture 2 - Introduction to Pandas & NumPy Tutorial

**H**                   : shows all keyboard shortcuts

**Enter**		    : Enter edit mode for the currently selected cell.

**Enter + Shift**	: Run the currently selected cell and move to the next one.

**A**		        : Add a new cell above the currently selected cell.

**B**		        : Add a new cell below the currently selected cell.

**M**		        : Change the current cell to Markdown.

**Y**               : Change the current cell to Code.


### Task1: Import Pandas library into your notebook.

In [1]:
import pandas as pd

### Task2: Check the current version of the library.

In [2]:
pd.__version__

'2.2.2'

In [3]:
!pip install --upgrade pandas

### Task3: Download “Stars.csv” from the link belove and import into your notebook.
'
https://tubcloud.tu-berlin.de/s/Byyrq9wpHrg5yKm/download/Stars.csv

In [4]:
df = pd.read_csv('https://tubcloud.tu-berlin.de/s/Byyrq9wpHrg5yKm/download/Stars.csv')
df

Temperature              L          R    A_M  Color Spectral_Class  Type
0           3068       0.002400     0.1700  16.12    Red              M     0
1           3042       0.000500     0.1542  16.60    Red              M     0
2           2600       0.000300     0.1020  18.70    Red              M     0
3           2800       0.000200     0.1600  16.65    Red              M     0
4           1939       0.000138     0.1030  20.06    Red              M     0
..           ...            ...        ...    ...    ...            ...   ...
235        38940  374830.000000  1356.0000  -9.93   Blue              O     5
236        30839  834042.000000  1194.0000 -10.63   Blue              O     5
237         8829  537493.000000  1423.0000 -10.73  White              A     5
238         9235  404940.000000  1112.0000 -11.23  White              A     5
239        37882  294903.000000  1783.0000  -7.80   Blue              O     5

[240 rows x 7 columns]

### Task4: Check the type of the DataFrame.

In [5]:
type(df)

pandas.core.frame.DataFrame

### Task5: Check the data structure of the DataFrame.
	-How many columns does the data contain?
	-How many rows does the data contain?
	-What data types are present in the data?
    
#### Hint: dataframe.info()

In [6]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 240 entries, 0 to 239
Data columns (total 7 columns):
 #   Column          Non-Null Count  Dtype  
---  ------          --------------  -----  
 0   Temperature     240 non-null    int64  
 1   L               240 non-null    float64
 2   R               240 non-null    float64
 3   A_M             240 non-null    float64
 4   Color           240 non-null    object 
 5   Spectral_Class  240 non-null    object 
 6   Type            240 non-null    int64  
dtypes: float64(3), int64(2), object(2)
memory usage: 13.2+ KB


### Task6: Check the shape of the DataFrame.


In [7]:
df.shape

(240, 7)

In [8]:
!pip install openpyxl --upgrade

### Task7: Download “robotics_component.xlsx” from the link belove and import into your notebook.

https://tubcloud.tu-berlin.de/s/JermLyzNEeMcS6G/download/robotics_component.xlsx

In [14]:
df2 = pd.read_excel('https://tubcloud.tu-berlin.de/s/JermLyzNEeMcS6G/download/robotics_component.xlsx', sheet_name='robotics_component')
df2

Component ID  Test Date Material Type  Stress Test Score  \
0           101 2023-10-01      Aluminum          89.376823   
1           102 2023-10-02       Plastic          83.127616   
2           103 2023-10-03         Steel          96.753190   
3           104 2023-10-04      Aluminum          98.909883   
4           105 2023-10-05       Plastic          81.503246   
5           106 2023-10-06       Plastic          93.751751   
6           107 2023-10-07       Plastic          85.866848   
7           108 2023-10-08       Plastic          87.041337   
8           109 2023-10-09         Steel          97.767899   
9           110 2023-10-10       Plastic          72.131082   

   Durability Rating (Pass/Fail) Warranty Period (Days) Usage Category  
0                          False               339 days     Industrial  
1                           True               100 days       Personal  
2                          False               178 days     Industrial  
3                           True               244 days       Personal  
4                          False               286 days       Personal  
5                          False               148 days     Industrial  
6                           True               148 days       Personal  
7                          False               289 days     Industrial  
8                          False               266 days     Industrial  
9                           True               186 days     Industrial

### Task8: Check the type of the DataFrame.

In [15]:
type(df2)

pandas.core.frame.DataFrame

### Task9: Export “robotics_component.xlsx” to as a CSV file.

In [16]:
df2.to_csv('robotics_component.csv')

### Task10: Import Numpy library into your notebook.

In [18]:
import numpy as np

### Task11: Check the current version of library.

In [19]:
np.__version__

'1.26.0'

### Task12: Create a 1D array.

In [21]:
arr1 = np.array([1, 2, 3, 4])
arr1

array([1, 2, 3, 4])

In [24]:
np.arange(5)

array([0, 1, 2, 3, 4])

### Task13: Create a 2D array.

In [23]:
arr2 = np.array([[1, 2, 3, 4],
                 [1, 2, 3, 4]])
arr2

array([[1, 2, 3, 4],
       [1, 2, 3, 4]])

### Task14: Create a 3D array.

In [25]:
arr3 = np.array([[[1, 2, 3, 4],
                 [1, 2, 3, 4]]])
arr3

array([[[1, 2, 3, 4],
        [1, 2, 3, 4]]])

In [29]:
arr3.ndim

3

In [30]:
arr3.shape

(1, 2, 4)

### Task15: Create a (3,4) array with zeros.

In [34]:
zeros = np.zeros((3, 4))

In [36]:
zeros.shape

(3, 4)

### Task16: Convert the following 1D array into a 2D array.

#### Hint: array.reshape()

In [37]:
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [40]:
arr.reshape((2, 5))

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

### Task17: Convert the following 1D array into a 3D array.

#### Hint: array.reshape()

In [58]:
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12])
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [66]:
arr = arr.reshape((2, 3, 2))
arr

array([[[ 1,  2],
        [ 3,  4],
        [ 5,  6]],

       [[ 7,  8],
        [ 9, 10],
        [11, 12]]])

In [65]:
arr.ndim

3

### Task18: Import pickle library into your notebook.

In [68]:
import pickle

### Task19: Create a Pickle File

In [69]:
data = [{'a': 1, 'b': 2, 'c':3}]

### Task20: Read a Pickle File

### Task20: Import json library into your notebook.


In [70]:
import json

### Task21: Read JSON File into a Pandas DataFrame

In [71]:
#Suppose you have a JSON file named sample_data.json with the following content:

file = [
    {"name": "Alice", "age": 30, "city": "New York"},
    {"name": "Bob", "age": 25, "city": "Los Angeles"},
    {"name": "Charlie", "age": 35, "city": "Chicago"}
]

In [75]:
df = pd.read_json('test.json')

In [76]:
df

name  age         city
0    Alice   30     New York
1      Bob   25  Los Angeles
2  Charlie   35      Chicago