# Introduction to Quality Data & Engineering with Python
## Lecture 2 - Introduction to Pandas & NumPy Tutorial

**H**                   : shows all keyboard shortcuts

**Enter**		    : Enter edit mode for the currently selected cell.

**Enter + Shift**	: Run the currently selected cell and move to the next one.

**A**		        : Add a new cell above the currently selected cell.

**B**		        : Add a new cell below the currently selected cell.

**M**		        : Change the current cell to Markdown.

**Y**               : Change the current cell to Code.


### Task1: Import Pandas library into your notebook.

In [1]:
import pandas as pd

### Task2: Check the current version of the library.

In [2]:
pd.__version__

'2.2.2'

In [3]:
#!pip install --upgrade pandas

     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 11.3/11.3 MB 30.8 MB/s eta 0:00:00a 0:00:01
  Attempting uninstall: pandas
    Found existing installation: pandas 2.2.1
    Uninstalling pandas-2.2.1:
      Successfully uninstalled pandas-2.2.1
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
streamlit 1.28.0 requires importlib-metadata<7,>=1.4, but you have importlib-metadata 7.1.0 which is incompatible.


### Task3: Download “Stars.csv” from the link belove and import into your notebook.

https://tubcloud.tu-berlin.de/s/Byyrq9wpHrg5yKm/download/Stars.csv

In [3]:
df = pd.read_csv("Stars.csv")

In [4]:
df

Temperature              L          R    A_M  Color Spectral_Class  Type
0           3068       0.002400     0.1700  16.12    Red              M     0
1           3042       0.000500     0.1542  16.60    Red              M     0
2           2600       0.000300     0.1020  18.70    Red              M     0
3           2800       0.000200     0.1600  16.65    Red              M     0
4           1939       0.000138     0.1030  20.06    Red              M     0
..           ...            ...        ...    ...    ...            ...   ...
235        38940  374830.000000  1356.0000  -9.93   Blue              O     5
236        30839  834042.000000  1194.0000 -10.63   Blue              O     5
237         8829  537493.000000  1423.0000 -10.73  White              A     5
238         9235  404940.000000  1112.0000 -11.23  White              A     5
239        37882  294903.000000  1783.0000  -7.80   Blue              O     5

[240 rows x 7 columns]

### Task4: Check the type of the DataFrame.

In [6]:
print(type(df))

<class 'pandas.core.frame.DataFrame'>


### Task5: Check the data structure of the DataFrame.
	-How many columns does the data contain?
	-How many rows does the data contain?
	-What data types are present in the data?
    
#### Hint: dataframe.info()

In [7]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 240 entries, 0 to 239
Data columns (total 7 columns):
 #   Column          Non-Null Count  Dtype  
---  ------          --------------  -----  
 0   Temperature     240 non-null    int64  
 1   L               240 non-null    float64
 2   R               240 non-null    float64
 3   A_M             240 non-null    float64
 4   Color           240 non-null    object 
 5   Spectral_Class  240 non-null    object 
 6   Type            240 non-null    int64  
dtypes: float64(3), int64(2), object(2)
memory usage: 13.2+ KB


### Task6: Check the shape of the DataFrame.


In [9]:
df.shape

(240, 7)

### Task7: Download “robotics_component.xlsx” from the link belove and import into your notebook.

https://tubcloud.tu-berlin.de/s/JermLyzNEeMcS6G/download/robotics_component.xlsx

In [12]:
df2 = pd.read_excel("robotics_component.xlsx", sheet_name="Sheet1")
df2

107 2023-10-07 00:00:00  Plastic  85.86684759258713   True  148 days  \
0  108          2023-10-08  Plastic          87.041337  False  289 days   
1  109          2023-10-09    Steel          97.767899  False  266 days   
2  110          2023-10-10  Plastic          72.131082   True  186 days   

     Personal  
0  Industrial  
1  Industrial  
2  Industrial

### Task8: Check the type of the DataFrame.

In [13]:
type(df2)

pandas.core.frame.DataFrame

### Task9: Export “robotics_component.xlsx” to as a CSV file.

In [14]:
df2.to_csv("robotics_component.csv")

### Task10: Import Numpy library into your notebook.

In [15]:
import numpy as np

### Task11: Check the current version of library.

In [16]:
np.__version__

'1.26.4'

### Task12: Create a 1D array.

In [18]:
arr = np.array([1,2,3,4])
arr

array([1, 2, 3, 4])

In [19]:
np.arange(5)

array([0, 1, 2, 3, 4])

In [20]:
np.arange(2,5)

array([2, 3, 4])

In [21]:
np.arange(2,10,2)

array([2, 4, 6, 8])

### Task13: Create a 2D array.

In [23]:
arr2 = np.array([[1, 2, 3, 4],[1, 2, 3, 4]])
arr2

array([[1, 2, 3, 4],
       [1, 2, 3, 4]])

In [24]:
arr2.shape

(2, 4)

In [26]:
arr2.ndim

2

### Task14: Create a 3D array.

In [27]:
arr3 = np.array([[[1,2,3,4],[5,6,7,8],[9,10,11,12]]])
arr3

array([[[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12]]])

In [28]:
arr3.ndim

3

In [29]:
arr3.shape

(1, 3, 4)

### Task15: Create a (3,4) array with zeros.

In [31]:
np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

### Task16: Convert the following 1D array into a 2D array.

#### Hint: array.reshape()

In [32]:
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [33]:
arr.ndim

1

In [38]:
arr_new = arr.reshape((2,5))
arr_new

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [39]:
arr_new.ndim

2

### Task17: Convert the following 1D array into a 3D array.

#### Hint: array.reshape()

In [40]:
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12])
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [42]:
arr = arr.reshape((2,3,2))
arr

array([[[ 1,  2],
        [ 3,  4],
        [ 5,  6]],

       [[ 7,  8],
        [ 9, 10],
        [11, 12]]])

In [43]:
arr.ndim

3

### Task18: Import pickle library into your notebook.

In [44]:
import pickle

### Task19: Create a Pickle File

In [45]:
# Creating a dictionary to pickle
data = [{'a': 1, 'b': 2, 'c': 3}]

In [46]:
# Serializing data and saving it to a pickle file
with open('data.pickle', 'wb') as f:
    pickle.dump(data, f)

### Task20: Read a Pickle File

In [47]:
# Reading data from a pickle file
with open('data.pickle', 'rb') as f:
    loaded_data = pickle.load(f)

print(loaded_data)

[{'a': 1, 'b': 2, 'c': 3}]


In [48]:
serialized = pickle.dumps(data) 
print(serialized)

b'\x80\x04\x95\x1a\x00\x00\x00\x00\x00\x00\x00]\x94}\x94(\x8c\x01a\x94K\x01\x8c\x01b\x94K\x02\x8c\x01c\x94K\x03ua.'


In [49]:
binary_string = b'\x80\x04\x95\x1a\x00\x00\x00\x00\x00\x00\x00]\x94}\x94(\x8c\x01a\x94K\x01\x8c\x01b\x94K\x02\x8c\x01c\x94K\x03ua.'
  
# Use loads to load the variable 
myvar = pickle.loads(binary_string) 
  
print(myvar) 

[{'a': 1, 'b': 2, 'c': 3}]


### Task20: Import json library into your notebook.


In [50]:
import json

### Task21: Read JSON File into a Pandas DataFrame

In [ ]:
#Suppose you have a JSON file named sample_data.json with the following content:

[
    {"name": "Alice", "age": 30, "city": "New York"},
    {"name": "Bob", "age": 25, "city": "Los Angeles"},
    {"name": "Charlie", "age": 35, "city": "Chicago"}
]

In [51]:
df_json = pd.read_json("sample_data.json")

In [52]:
df_json

name  age         city
0    Alice   30     New York
1      Bob   25  Los Angeles
2  Charlie   35      Chicago