# Introduction to Quality Data & Engineering with Python
## Lecture 3 - Selecting and Filtering Tutorial

## Numpy

### Task1: Import Numpy library into your notebook.

In [1]:
import numpy as np

### Task2: Create a 1D numpy array

output: array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [2]:
arr = np.array([1,2,3,4,5,6,7,8,9])

In [3]:
arr

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

### Task3: Access the first element of the array

In [4]:
arr[0]

1

### Task4: Access the last element of the array

In [5]:
arr[-1]

9

In [6]:
arr[8]

9

### Task5: Access the first two element of the array

In [7]:
arr[:2]

array([1, 2])

In [8]:
arr[0:2]

array([1, 2])

### Task5: Create a 2D numpy array

output: array([[ 1,  2,  3,  4],
               [ 5,  6,  7,  8],
               [ 9, 10, 11, 12]])

In [9]:
arr = np.array([
    [1, 2, 3, 4],
    [5, 6, 7, 8],
    [9, 10, 11, 12]])

In [10]:
arr

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

### Task6: Accessing an element at specific index

In [11]:
arr[0,0]

1

In [12]:
arr[2,2]

11

### Task7: Slice rows from index 1 to 2 and all columns

In [13]:
arr[1:3,:]

array([[ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

### Task8: Slice all rows and columns from index 2 to 4

In [14]:
arr[:,2:4]

array([[ 3,  4],
       [ 7,  8],
       [11, 12]])

In [15]:
arr[:,2:]

array([[ 3,  4],
       [ 7,  8],
       [11, 12]])

## Pandas

### Task1: Import Pandas library into your notebook.

In [16]:
import pandas as pd

### Task2: Download “FuelConsumption_v2.csv” from the link belove and import into your notebook.

https://tubcloud.tu-berlin.de/s/8A9p9rMPgscBocB/download/FuelConsumption_v2.csv

In [17]:
df = pd.read_csv('FuelConsumption_v2.csv')

### Task3: Display the first 5 rows your DataFrame

In [18]:
df.head()

Unnamed: 0  Year  Brand    Model Vehicle_Class  Engine_Size  Cylinders  \
0           0  2000  ACURA    1.6EL       COMPACT          1.6          4   
1           1  2000  ACURA    1.6EL       COMPACT          1.6          4   
2           2  2000  ACURA    3.2TL      MID-SIZE          3.2          6   
3           3  2000  ACURA    3.5RL      MID-SIZE          3.5          6   
4           4  2000  ACURA  INTEGRA    SUBCOMPACT          1.8          4   

  Transmission Fuel  Fuel_Consumption  CO2_Emissions  
0           A4    X              10.5            216  
1           M5    X               9.8            205  
2          AS5    Z              13.7            265  
3           A4    Z              15.0            301  
4           A4    X              11.4            230

### Task4: Display the last 5 rows your DataFrame

In [19]:
df.tail()

Unnamed: 0  Year  Brand           Model             Vehicle_Class  \
634         634  2000  VOLVO   V70 AWD TURBO  STATION WAGON - MID-SIZE   
635         635  2000  VOLVO   V70 GLT TURBO  STATION WAGON - MID-SIZE   
636         636  2000  VOLVO    V70 T5 TURBO  STATION WAGON - MID-SIZE   
637         637  2000  VOLVO    V70 T5 TURBO  STATION WAGON - MID-SIZE   
638         638  2000  VOLVO  V70R AWD TURBO  STATION WAGON - MID-SIZE   

     Engine_Size  Cylinders Transmission Fuel  Fuel_Consumption  CO2_Emissions  
634          2.4          5           A4    Z              14.4            288  
635          2.4          5           A4    Z              13.6            274  
636          2.3          5           A4    Z              13.9            274  
637          2.3          5           M5    Z              13.0            260  
638          2.4          5           A5    Z              14.7            299

### Task5: Sort values by "Fuel_Consumption".

In [20]:
df.sort_values(by ="Fuel_Consumption")

Unnamed: 0  Year       Brand                  Model Vehicle_Class  \
328         328  2000       HONDA                INSIGHT    SUBCOMPACT   
591         591  2000  VOLKSWAGEN        GOLF TDI DIESEL       COMPACT   
603         603  2000  VOLKSWAGEN       JETTA TDI DIESEL       COMPACT   
609         609  2000  VOLKSWAGEN  NEW BEETLE TDI DIESEL    SUBCOMPACT   
114         114  2000   CHEVROLET                  METRO    SUBCOMPACT   
..          ...   ...         ...                    ...           ...   
212         212  2000     FERRARI                456 MGT    SUBCOMPACT   
214         214  2000     FERRARI               456 MGTA    SUBCOMPACT   
213         213  2000     FERRARI               456 MGTA    SUBCOMPACT   
211         211  2000     FERRARI                456 MGT    SUBCOMPACT   
215         215  2000     FERRARI          550 MARANELLO    SUBCOMPACT   

     Engine_Size  Cylinders Transmission Fuel  Fuel_Consumption  CO2_Emissions  
328          1.0          3           M5    X               4.9            104  
591          1.9          4           M5    D               6.7            165  
603          1.9          4           M5    D               6.7            165  
609          1.9          4           M5    D               6.7            165  
114          1.0          3           M5    X               7.1            147  
..           ...        ...          ...  ...               ...            ...  
212          5.5         12           M6    Z              26.3            495  
214          5.5         12           M6    Z              26.3            495  
213          5.5         12           A4    Z              26.7            513  
211          5.5         12           A4    Z              26.7            513  
215          5.5         12           M6    Z              30.2            582  

[639 rows x 11 columns]

In [21]:
df.sort_values(by ="Fuel_Consumption", ascending=False)

Unnamed: 0  Year       Brand                  Model Vehicle_Class  \
215         215  2000     FERRARI          550 MARANELLO    SUBCOMPACT   
213         213  2000     FERRARI               456 MGTA    SUBCOMPACT   
211         211  2000     FERRARI                456 MGT    SUBCOMPACT   
212         212  2000     FERRARI                456 MGT    SUBCOMPACT   
214         214  2000     FERRARI               456 MGTA    SUBCOMPACT   
..          ...   ...         ...                    ...           ...   
114         114  2000   CHEVROLET                  METRO    SUBCOMPACT   
609         609  2000  VOLKSWAGEN  NEW BEETLE TDI DIESEL    SUBCOMPACT   
603         603  2000  VOLKSWAGEN       JETTA TDI DIESEL       COMPACT   
591         591  2000  VOLKSWAGEN        GOLF TDI DIESEL       COMPACT   
328         328  2000       HONDA                INSIGHT    SUBCOMPACT   

     Engine_Size  Cylinders Transmission Fuel  Fuel_Consumption  CO2_Emissions  
215          5.5         12           M6    Z              30.2            582  
213          5.5         12           A4    Z              26.7            513  
211          5.5         12           A4    Z              26.7            513  
212          5.5         12           M6    Z              26.3            495  
214          5.5         12           M6    Z              26.3            495  
..           ...        ...          ...  ...               ...            ...  
114          1.0          3           M5    X               7.1            147  
609          1.9          4           M5    D               6.7            165  
603          1.9          4           M5    D               6.7            165  
591          1.9          4           M5    D               6.7            165  
328          1.0          3           M5    X               4.9            104  

[639 rows x 11 columns]

### Task6: Delete the "Unnamed: 0" column.

In [22]:
df = df.drop("Unnamed: 0",axis=1)

In [23]:
df.head()

Year  Brand    Model Vehicle_Class  Engine_Size  Cylinders Transmission  \
0  2000  ACURA    1.6EL       COMPACT          1.6          4           A4   
1  2000  ACURA    1.6EL       COMPACT          1.6          4           M5   
2  2000  ACURA    3.2TL      MID-SIZE          3.2          6          AS5   
3  2000  ACURA    3.5RL      MID-SIZE          3.5          6           A4   
4  2000  ACURA  INTEGRA    SUBCOMPACT          1.8          4           A4   

  Fuel  Fuel_Consumption  CO2_Emissions  
0    X              10.5            216  
1    X               9.8            205  
2    Z              13.7            265  
3    Z              15.0            301  
4    X              11.4            230

### Slicing by columns
### Task7: Select specific columns by their names

Hint: Do not use loc or iloc

In [24]:
df_brand = df[["Brand","Model","Year"]]

In [25]:
df_brand

Brand           Model  Year
0    ACURA           1.6EL  2000
1    ACURA           1.6EL  2000
2    ACURA           3.2TL  2000
3    ACURA           3.5RL  2000
4    ACURA         INTEGRA  2000
..     ...             ...   ...
634  VOLVO   V70 AWD TURBO  2000
635  VOLVO   V70 GLT TURBO  2000
636  VOLVO    V70 T5 TURBO  2000
637  VOLVO    V70 T5 TURBO  2000
638  VOLVO  V70R AWD TURBO  2000

[639 rows x 3 columns]

### Slicing by rows using .loc[ ]
### Task7: Select rows based on labels (index and column names)

In [26]:
selected_rows_loc = df.loc[:,["Brand","Model","Year"]]
selected_rows_loc

Brand           Model  Year
0    ACURA           1.6EL  2000
1    ACURA           1.6EL  2000
2    ACURA           3.2TL  2000
3    ACURA           3.5RL  2000
4    ACURA         INTEGRA  2000
..     ...             ...   ...
634  VOLVO   V70 AWD TURBO  2000
635  VOLVO   V70 GLT TURBO  2000
636  VOLVO    V70 T5 TURBO  2000
637  VOLVO    V70 T5 TURBO  2000
638  VOLVO  V70R AWD TURBO  2000

[639 rows x 3 columns]

### Slicing by rows and columns using .loc[ ]
### Task8: Select specific rows and columns based on labels

In [27]:
df.loc[[0,1,3], ["Brand","Model","Year"]]

Brand  Model  Year
0  ACURA  1.6EL  2000
1  ACURA  1.6EL  2000
3  ACURA  3.5RL  2000

### Slicing by rows and columns using .iloc[ ]
### Task9: Select specific rows and columns based on integer positions

In [28]:
df.iloc[[0,1,3], [1,2,0]]

Brand  Model  Year
0  ACURA  1.6EL  2000
1  ACURA  1.6EL  2000
3  ACURA  3.5RL  2000

In [29]:
df.iloc[[0,1,3], 0:3]

Year  Brand  Model
0  2000  ACURA  1.6EL
1  2000  ACURA  1.6EL
3  2000  ACURA  3.5RL

### Python Comparison Operators

In [30]:
# ==   :  Equal - Compares if two values are equal.
# !=   :  Not Equal - Compares if two values are not equal.
# <    :  Less Than - Checks if the value on the left is less than the value on the right.
# >    :  Greater Than - Checks if the value on the left is greater than the value on the right.
# <=   :  Less Than or Equal To - Checks if the value on the left is less than or equal to the value on the right.
# >=   :  Greater Than or Equal To - Checks if the value on the left is greater than or equal to the value on the right.


### Boolean Operators

In [31]:
# AND ( & ) - Both conditions must be met:  True if both operands are True. Otherwise, False. 
# OR ( | ) - At least one condition must be met: False only if both operands are False. 
# NOT ( not ) - Reverse the condition: If the operand is True, it becomes False, if the operand is False, it becomes True.

### Task10: Filter rows where Engine_Size is greater than 2.0.

In [32]:
df[df["Engine_Size"] > 2.0]

Year  Brand           Model             Vehicle_Class  Engine_Size  \
2    2000  ACURA           3.2TL                  MID-SIZE          3.2   
3    2000  ACURA           3.5RL                  MID-SIZE          3.5   
7    2000  ACURA             NSX                SUBCOMPACT          3.0   
8    2000  ACURA             NSX                SUBCOMPACT          3.2   
11   2000   AUDI              A4                   COMPACT          2.8   
..    ...    ...             ...                       ...          ...   
634  2000  VOLVO   V70 AWD TURBO  STATION WAGON - MID-SIZE          2.4   
635  2000  VOLVO   V70 GLT TURBO  STATION WAGON - MID-SIZE          2.4   
636  2000  VOLVO    V70 T5 TURBO  STATION WAGON - MID-SIZE          2.3   
637  2000  VOLVO    V70 T5 TURBO  STATION WAGON - MID-SIZE          2.3   
638  2000  VOLVO  V70R AWD TURBO  STATION WAGON - MID-SIZE          2.4   

     Cylinders Transmission Fuel  Fuel_Consumption  CO2_Emissions  
2            6          AS5    Z              13.7            265  
3            6           A4    Z              15.0            301  
7            6          AS4    Z              15.2            306  
8            6           M6    Z              15.4            306  
11           6           A5    Z              14.6            285  
..         ...          ...  ...               ...            ...  
634          5           A4    Z              14.4            288  
635          5           A4    Z              13.6            274  
636          5           A4    Z              13.9            274  
637          5           M5    Z              13.0            260  
638          5           A5    Z              14.7            299  

[500 rows x 10 columns]

### Task11: Filter rows where Vehicle_Class is 'SUV'.

In [33]:
df[df["Vehicle_Class"] == 'SUV']

Year      Brand              Model Vehicle_Class  Engine_Size  Cylinders  \
54   2000        BMW                 X5           SUV          4.4          8   
69   2000   CADILLAC       ESCALADE 4X4           SUV          5.7          8   
75   2000  CHEVROLET             BLAZER           SUV          4.3          6   
76   2000  CHEVROLET             BLAZER           SUV          4.3          6   
77   2000  CHEVROLET         BLAZER 4X4           SUV          4.3          6   
..    ...        ...                ...           ...          ...        ...   
562  2000     TOYOTA           RAV4 4X4           SUV          2.0          4   
563  2000     TOYOTA      RAV4 SOFT TOP           SUV          2.0          4   
564  2000     TOYOTA      RAV4 SOFT TOP           SUV          2.0          4   
565  2000     TOYOTA  RAV4 SOFT TOP 4X4           SUV          2.0          4   
566  2000     TOYOTA  RAV4 SOFT TOP 4X4           SUV          2.0          4   

    Transmission Fuel  Fuel_Consumption  CO2_Emissions  
54            A5    Z              14.9            294  
69            A4    X              21.2            430  
75            A4    X              16.2            336  
76            M5    X              16.3            327  
77            A4    X              16.9            350  
..           ...  ...               ...            ...  
562           M5    X              12.1            258  
563           A4    X              11.3            235  
564           M5    X              11.2            232  
565           A4    X              11.8            251  
566           M5    X              11.9            253  

[97 rows x 10 columns]

In [34]:
df.loc[df["Vehicle_Class"] == 'SUV']

Year      Brand              Model Vehicle_Class  Engine_Size  Cylinders  \
54   2000        BMW                 X5           SUV          4.4          8   
69   2000   CADILLAC       ESCALADE 4X4           SUV          5.7          8   
75   2000  CHEVROLET             BLAZER           SUV          4.3          6   
76   2000  CHEVROLET             BLAZER           SUV          4.3          6   
77   2000  CHEVROLET         BLAZER 4X4           SUV          4.3          6   
..    ...        ...                ...           ...          ...        ...   
562  2000     TOYOTA           RAV4 4X4           SUV          2.0          4   
563  2000     TOYOTA      RAV4 SOFT TOP           SUV          2.0          4   
564  2000     TOYOTA      RAV4 SOFT TOP           SUV          2.0          4   
565  2000     TOYOTA  RAV4 SOFT TOP 4X4           SUV          2.0          4   
566  2000     TOYOTA  RAV4 SOFT TOP 4X4           SUV          2.0          4   

    Transmission Fuel  Fuel_Consumption  CO2_Emissions  
54            A5    Z              14.9            294  
69            A4    X              21.2            430  
75            A4    X              16.2            336  
76            M5    X              16.3            327  
77            A4    X              16.9            350  
..           ...  ...               ...            ...  
562           M5    X              12.1            258  
563           A4    X              11.3            235  
564           M5    X              11.2            232  
565           A4    X              11.8            251  
566           M5    X              11.9            253  

[97 rows x 10 columns]

In [35]:
df[df.iloc[:,3] == 'SUV']

Year      Brand              Model Vehicle_Class  Engine_Size  Cylinders  \
54   2000        BMW                 X5           SUV          4.4          8   
69   2000   CADILLAC       ESCALADE 4X4           SUV          5.7          8   
75   2000  CHEVROLET             BLAZER           SUV          4.3          6   
76   2000  CHEVROLET             BLAZER           SUV          4.3          6   
77   2000  CHEVROLET         BLAZER 4X4           SUV          4.3          6   
..    ...        ...                ...           ...          ...        ...   
562  2000     TOYOTA           RAV4 4X4           SUV          2.0          4   
563  2000     TOYOTA      RAV4 SOFT TOP           SUV          2.0          4   
564  2000     TOYOTA      RAV4 SOFT TOP           SUV          2.0          4   
565  2000     TOYOTA  RAV4 SOFT TOP 4X4           SUV          2.0          4   
566  2000     TOYOTA  RAV4 SOFT TOP 4X4           SUV          2.0          4   

    Transmission Fuel  Fuel_Consumption  CO2_Emissions  
54            A5    Z              14.9            294  
69            A4    X              21.2            430  
75            A4    X              16.2            336  
76            M5    X              16.3            327  
77            A4    X              16.9            350  
..           ...  ...               ...            ...  
562           M5    X              12.1            258  
563           A4    X              11.3            235  
564           M5    X              11.2            232  
565           A4    X              11.8            251  
566           M5    X              11.9            253  

[97 rows x 10 columns]

In [36]:
df.loc[df.iloc[:,3] == 'SUV']

Year      Brand              Model Vehicle_Class  Engine_Size  Cylinders  \
54   2000        BMW                 X5           SUV          4.4          8   
69   2000   CADILLAC       ESCALADE 4X4           SUV          5.7          8   
75   2000  CHEVROLET             BLAZER           SUV          4.3          6   
76   2000  CHEVROLET             BLAZER           SUV          4.3          6   
77   2000  CHEVROLET         BLAZER 4X4           SUV          4.3          6   
..    ...        ...                ...           ...          ...        ...   
562  2000     TOYOTA           RAV4 4X4           SUV          2.0          4   
563  2000     TOYOTA      RAV4 SOFT TOP           SUV          2.0          4   
564  2000     TOYOTA      RAV4 SOFT TOP           SUV          2.0          4   
565  2000     TOYOTA  RAV4 SOFT TOP 4X4           SUV          2.0          4   
566  2000     TOYOTA  RAV4 SOFT TOP 4X4           SUV          2.0          4   

    Transmission Fuel  Fuel_Consumption  CO2_Emissions  
54            A5    Z              14.9            294  
69            A4    X              21.2            430  
75            A4    X              16.2            336  
76            M5    X              16.3            327  
77            A4    X              16.9            350  
..           ...  ...               ...            ...  
562           M5    X              12.1            258  
563           A4    X              11.3            235  
564           M5    X              11.2            232  
565           A4    X              11.8            251  
566           M5    X              11.9            253  

[97 rows x 10 columns]

### Task12: Filter rows where CO2_Emissions is less than or equal to 250.

In [37]:
df[df["CO2_Emissions"]<=250]

Year       Brand                  Model             Vehicle_Class  \
0    2000       ACURA                  1.6EL                   COMPACT   
1    2000       ACURA                  1.6EL                   COMPACT   
4    2000       ACURA                INTEGRA                SUBCOMPACT   
5    2000       ACURA                INTEGRA                SUBCOMPACT   
6    2000       ACURA     INTEGRA GSR/TYPE R                SUBCOMPACT   
..    ...         ...                    ...                       ...   
607  2000  VOLKSWAGEN             NEW BEETLE                SUBCOMPACT   
608  2000  VOLKSWAGEN  NEW BEETLE TDI DIESEL                SUBCOMPACT   
609  2000  VOLKSWAGEN  NEW BEETLE TDI DIESEL                SUBCOMPACT   
611  2000  VOLKSWAGEN                 PASSAT                  MID-SIZE   
615  2000  VOLKSWAGEN           PASSAT WAGON  STATION WAGON - MID-SIZE   

     Engine_Size  Cylinders Transmission Fuel  Fuel_Consumption  CO2_Emissions  
0            1.6          4           A4    X              10.5            216  
1            1.6          4           M5    X               9.8            205  
4            1.8          4           A4    X              11.4            230  
5            1.8          4           M5    X              10.6            219  
6            1.8          4           M5    Z              10.8            223  
..           ...        ...          ...  ...               ...            ...  
607          2.0          4           M5    X              11.2            228  
608          1.9          4           A4    D               8.1            192  
609          1.9          4           M5    D               6.7            165  
611          1.8          4           M5    Z              11.2            225  
615          1.8          4           M5    Z              11.2            225  

[148 rows x 10 columns]

### Task13: Filter rows where Engine_Size is greater than 2.0 and Fuel is 'Z'.

In [38]:
df[(df["Engine_Size"] > 2.0) & (df["Fuel"] == "Z")]

Year  Brand           Model             Vehicle_Class  Engine_Size  \
2    2000  ACURA           3.2TL                  MID-SIZE          3.2   
3    2000  ACURA           3.5RL                  MID-SIZE          3.5   
7    2000  ACURA             NSX                SUBCOMPACT          3.0   
8    2000  ACURA             NSX                SUBCOMPACT          3.2   
11   2000   AUDI              A4                   COMPACT          2.8   
..    ...    ...             ...                       ...          ...   
634  2000  VOLVO   V70 AWD TURBO  STATION WAGON - MID-SIZE          2.4   
635  2000  VOLVO   V70 GLT TURBO  STATION WAGON - MID-SIZE          2.4   
636  2000  VOLVO    V70 T5 TURBO  STATION WAGON - MID-SIZE          2.3   
637  2000  VOLVO    V70 T5 TURBO  STATION WAGON - MID-SIZE          2.3   
638  2000  VOLVO  V70R AWD TURBO  STATION WAGON - MID-SIZE          2.4   

     Cylinders Transmission Fuel  Fuel_Consumption  CO2_Emissions  
2            6          AS5    Z              13.7            265  
3            6           A4    Z              15.0            301  
7            6          AS4    Z              15.2            306  
8            6           M6    Z              15.4            306  
11           6           A5    Z              14.6            285  
..         ...          ...  ...               ...            ...  
634          5           A4    Z              14.4            288  
635          5           A4    Z              13.6            274  
636          5           A4    Z              13.9            274  
637          5           M5    Z              13.0            260  
638          5           A5    Z              14.7            299  

[152 rows x 10 columns]

In [39]:
df[(df["Engine_Size"] > 2.0) & (df["Fuel"] == "Z")].head(10)

Year  Brand             Model             Vehicle_Class  Engine_Size  \
2   2000  ACURA             3.2TL                  MID-SIZE          3.2   
3   2000  ACURA             3.5RL                  MID-SIZE          3.5   
7   2000  ACURA               NSX                SUBCOMPACT          3.0   
8   2000  ACURA               NSX                SUBCOMPACT          3.2   
11  2000   AUDI                A4                   COMPACT          2.8   
12  2000   AUDI                A4                   COMPACT          2.8   
15  2000   AUDI        A4 QUATTRO                   COMPACT          2.8   
16  2000   AUDI        A4 QUATTRO                   COMPACT          2.8   
17  2000   AUDI                A6                  MID-SIZE          2.8   
18  2000   AUDI  A6 AVANT QUATTRO  STATION WAGON - MID-SIZE          2.8   

    Cylinders Transmission Fuel  Fuel_Consumption  CO2_Emissions  
2           6          AS5    Z              13.7            265  
3           6           A4    Z              15.0            301  
7           6          AS4    Z              15.2            306  
8           6           M6    Z              15.4            306  
11          6           A5    Z              14.6            285  
12          6           M5    Z              13.2            260  
15          6           A5    Z              14.9            292  
16          6           M5    Z              14.3            288  
17          6           A5    Z              15.0            294  
18          6           A5    Z              15.4            306

### Task14: Filter rows where Vehicle_Class is 'COMPACT' or 'MID-SIZE'.

In [40]:
df[(df['Vehicle_Class'] == "COMPACT") | (df['Vehicle_Class'] == "MID-SIZE")]

Year  Brand          Model Vehicle_Class  Engine_Size  Cylinders  \
0    2000  ACURA          1.6EL       COMPACT          1.6          4   
1    2000  ACURA          1.6EL       COMPACT          1.6          4   
2    2000  ACURA          3.2TL      MID-SIZE          3.2          6   
3    2000  ACURA          3.5RL      MID-SIZE          3.5          6   
9    2000   AUDI             A4       COMPACT          1.8          4   
..    ...    ...            ...           ...          ...        ...   
627  2000  VOLVO  S70 GLT TURBO      MID-SIZE          2.4          5   
628  2000  VOLVO   S70 T5 TURBO      MID-SIZE          2.3          5   
629  2000  VOLVO   S70 T5 TURBO      MID-SIZE          2.3          5   
630  2000  VOLVO        S80 2.9      MID-SIZE          2.9          6   
631  2000  VOLVO        S80 T-6      MID-SIZE          2.8          6   

    Transmission Fuel  Fuel_Consumption  CO2_Emissions  
0             A4    X              10.5            216  
1             M5    X               9.8            205  
2            AS5    Z              13.7            265  
3             A4    Z              15.0            301  
9             A5    Z              12.9            251  
..           ...  ...               ...            ...  
627           A4    Z              13.6            274  
628           A4    Z              13.9            274  
629           M5    Z              13.0            260  
630           A4    Z              14.5            285  
631          AS4    Z              15.1            297  

[182 rows x 10 columns]

### Final Task: Find rows with specified ('STATION WAGON - MID-SIZE', 'STATION WAGON - SMALL') values in 'Vehicle_Class' column and replace values into 'STATION WAGON'.

In [41]:
rows_to_update = (df['Vehicle_Class'] == 'STATION WAGON - MID-SIZE') | (df['Vehicle_Class'] == 'STATION WAGON - SMALL')

In [42]:
rows_to_update

0      False
1      False
2      False
3      False
4      False
       ...  
634     True
635     True
636     True
637     True
638     True
Name: Vehicle_Class, Length: 639, dtype: bool

In [43]:
df.loc[rows_to_update, 'Vehicle_Class'] = 'STATION WAGON'

In [44]:
df.tail(10)

Year  Brand           Model  Vehicle_Class  Engine_Size  Cylinders  \
629  2000  VOLVO    S70 T5 TURBO       MID-SIZE          2.3          5   
630  2000  VOLVO         S80 2.9       MID-SIZE          2.9          6   
631  2000  VOLVO         S80 T-6       MID-SIZE          2.8          6   
632  2000  VOLVO             V70  STATION WAGON          2.4          5   
633  2000  VOLVO             V70  STATION WAGON          2.4          5   
634  2000  VOLVO   V70 AWD TURBO  STATION WAGON          2.4          5   
635  2000  VOLVO   V70 GLT TURBO  STATION WAGON          2.4          5   
636  2000  VOLVO    V70 T5 TURBO  STATION WAGON          2.3          5   
637  2000  VOLVO    V70 T5 TURBO  STATION WAGON          2.3          5   
638  2000  VOLVO  V70R AWD TURBO  STATION WAGON          2.4          5   

    Transmission Fuel  Fuel_Consumption  CO2_Emissions  
629           M5    Z              13.0            260  
630           A4    Z              14.5            285  
631          AS4    Z              15.1            297  
632           A5    Z              13.2            262  
633           M5    Z              12.6            251  
634           A4    Z              14.4            288  
635           A4    Z              13.6            274  
636           A4    Z              13.9            274  
637           M5    Z              13.0            260  
638           A5    Z              14.7            299

In [45]:
df["Vehicle_Class"].value_counts()

Vehicle_Class
COMPACT                    105
SUBCOMPACT                 104
SUV                         97
PICKUP TRUCK - STANDARD     92
MID-SIZE                    77
STATION WAGON               38
FULL-SIZE                   28
MINIVAN                     26
VAN - CARGO                 23
VAN - PASSENGER             17
MINICOMPACT                 11
PICKUP TRUCK - SMALL        11
TWO-SEATER                  10
Name: count, dtype: int64

![Bonus Tasks!](https://www.shareicon.net/data/512x512/2016/04/11/748070_cup_512x512.png)

### Bonus Tasks

Dataset: https://tubcloud.tu-berlin.de/s/SgiKAseqGjqjyxT/download/Extended_Engineering_Materials.xlsx

#### Task 1: Importing Data

-   Objective: Learn how to import data from an Excel file using pandas.
-   Instructions: Use `pandas.read_excel()` to load the dataset into a DataFrame.

#### Task 2: Examining the Data

-   Objective: Understand the structure and summary of the dataset.
-   Instructions:
    -   Use the `.shape` attribute to find the number of rows and columns in the DataFrame.
    -   Use the `.info()` method to get a concise summary of the DataFrame, including the type of index, column types, non-null values, and memory usage.

#### Task 3: Selecting Data

-   Objective: Learn to select columns and rows from the DataFrame.
-   Instructions:
    -   Select the "Material" and "Density" columns and display them.
    -   Select the first and last 5 rows of the DataFrame using slicing.

#### Task 4: Filtering Data

-   Objective: Apply conditions to filter data based on column values.
-   Instructions:
    -   Filter and display materials with a Tensile Strength greater than 500 MPa.
    -   Filter and display materials that are used in 'Aerospace' applications.
    -   Filter and display Silicon material with a Density lower than 3.